# Generated by Django 2.0.2 on 2018-04-24 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('reporting_frequency', models.IntegerField(default=0)),
                ('quarter_order', models.IntegerField(default=0)),
                ('challenge_solver', models.CharField(default='N/A', max_length=200)),
                ('ojt_perfomed', models.IntegerField(default=0)),
                ('policy_compliance', models.IntegerField(default=0)),
                ('non_compliance_reason', models.TextField(default='N/A')),
                ('new_anc_moh711', models.IntegerField(default=0)),
                ('nets_anc_moh711', models.IntegerField(default=0)),
                ('nets_anc_fnprc', models.IntegerField(default=0)),
                ('nets_anc_variance', models.IntegerField(default=0)),
                ('new_cwc_moh710', models.IntegerField(default=0)),
                ('nets_cwc_moh711', models.IntegerField(default=0)),
                ('nets_cwc_fnprc', models.IntegerField(default=0)),
                ('nets_cwc_variance', models.IntegerField(default=0)),
                ('book_bal', models.IntegerField(default=0)),
                ('physical_count', models.IntegerField(default=0)),
                ('balance_variance', models.IntegerField(default=0)),
                ('bal_variance_reason', models.TextField(default='N/A')),
                ('ld_quantity', models.IntegerField(default=0)),
                ('ld_invoice_no', models.CharField(default='N/A', max_length=200)),
                ('ld_date', models.DateField()),
                ('lld_quantity', models.IntegerField(default=0)),
                ('lld_invoice_no', models.CharField(default='N/A', max_length=200)),
                ('lld_date', models.DateField()),
                ('amc', models.FloatField(default=0.0)),
                ('months_of_stock', models.FloatField(default=0.0)),
                ('confirmable_cwc', models.CharField(max_length=200)),
                ('confirmable_anc', models.CharField(max_length=200)),
                ('nets_stored_in', models.CharField(max_length=200)),
                ('store_type', models.CharField(max_length=200)),
                ('stock_control_card', models.IntegerField(default=0)),
                ('store_access', models.CharField(default='', max_length=200)),
                ('pests_risk', models.CharField(default='', max_length=200)),
                ('fire_prevention', models.IntegerField(default=0)),
                ('fire_prevention_mechanism', models.CharField(max_length=200)),
                ('other_remarks', models.TextField(default='N/A')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facilities')),
                ('supervisor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
