# Generated by Django 2.0.2 on 2018-05-10 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ld_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
