# Generated by Django 2.0.2 on 2018-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20180312_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='store_access',
            field=models.CharField(default='', max_length=200),
        ),
    ]
