# Generated by Django 2.0.2 on 2018-05-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20180510_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='other_remarks',
            field=models.TextField(),
        ),
    ]
