# Generated by Django 2.0.2 on 2018-05-10 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20180510_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ld_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ld_invoice_no',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ld_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_invoice_no',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
