# Generated by Django 2.0.2 on 2018-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20180510_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='other_remarks',
            field=models.TextField(default=''),
        ),
    ]
