# Generated by Django 2.0.2 on 2018-05-10 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_auto_20180510_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='ld_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ld_invoice_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ld_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_invoice_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
