# Generated by Django 2.0.2 on 2018-05-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_auto_20180510_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='other_remarks',
        ),
    ]
