# Generated by Django 2.0.2 on 2018-05-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_visit_other_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='other_remarks',
            field=models.TextField(null=True),
        ),
    ]
