# Generated by Django 2.0.2 on 2018-05-15 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_auto_20180515_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='lld_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='lld_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
