# Generated by Django 2.0.2 on 2018-05-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_auto_20180515_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='nets_stored_in',
        ),
    ]
