# Generated by Django 2.0.2 on 2018-10-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_remove_visit_nets_stored_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='risk_level',
            field=models.CharField(default='Low', max_length=10),
        ),
    ]
