# Generated by Django 2.0.2 on 2018-03-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0003_facilities_facility_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=5)),
                ('bal_bf', models.IntegerField(default=0)),
                ('cwc_nets', models.IntegerField(default=0)),
                ('anc_nets', models.IntegerField(default=0)),
                ('others_nets', models.IntegerField(default=0)),
                ('bal_cf', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete='CASCADE', to='facilities.Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Nets_distributed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nets_issued', models.IntegerField()),
                ('date_issued', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete='CASCADE', to='facilities.Facilities')),
            ],
        ),
    ]
