# Generated by Django 2.0.2 on 2018-04-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_month', models.IntegerField()),
                ('dist_year', models.CharField(max_length=5)),
                ('bal_bf', models.IntegerField(default=0)),
                ('cwc_nets', models.IntegerField(default=0)),
                ('anc_nets', models.IntegerField(default=0)),
                ('others_nets', models.IntegerField(default=0)),
                ('total_nets', models.IntegerField(default=0)),
                ('bal_cf', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Nets_distributed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default='', max_length=200)),
                ('nets_issued', models.IntegerField()),
                ('donor_code', models.CharField(default='', max_length=20)),
                ('date_issued', models.DateField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('stock_balance', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='nets_distributed',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.Warehouse'),
        ),
    ]
