# Generated by Django 2.0.2 on 2018-03-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution_report',
            old_name='month',
            new_name='dist_month',
        ),
        migrations.RenameField(
            model_name='distribution_report',
            old_name='year',
            new_name='dist_year',
        ),
    ]
