# Generated by Django 2.0.2 on 2018-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='county',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
