# Generated by Django 2.0.2 on 2018-04-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_warehouse_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Counties'),
        ),
    ]
