# Generated by Django 2.0.2 on 2018-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_auto_20180308_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution_report',
            name='total_nets',
            field=models.IntegerField(default=0),
        ),
    ]
