# Generated by Django 2.0.2 on 2018-04-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_auto_20180424_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocking_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=200)),
                ('nets_quantity', models.IntegerField(default=0)),
                ('date_stocked', models.DateField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.Warehouse')),
            ],
        ),
    ]
