# Generated by Django 2.0.2 on 2018-03-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_distribution_report_total_nets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution_report',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facilities'),
        ),
        migrations.AlterField(
            model_name='nets_distributed',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.Facilities'),
        ),
    ]
