# Generated by Django 2.0.2 on 2018-03-20 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_auto_20180312_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='nets_distributed',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 3, 20, 19, 40, 3, 874400)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nets_distributed',
            name='invoice_no',
            field=models.CharField(default='', max_length=200),
        ),
    ]
