# Generated by Django 2.0.2 on 2018-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_stocking_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nets_distributed',
            name='warehouse',
            field=models.CharField(default='', max_length=255),
        ),
    ]
