# Generated by Django 2.0.2 on 2018-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_nets_donated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.IntegerField()),
                ('target_year', models.CharField(max_length=5)),
                ('donor', models.CharField(max_length=255)),
                ('target', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
