# Generated by Django 2.0.2 on 2019-09-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_distribution_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='nets_distributed',
            name='invoice_type',
            field=models.CharField(default='invoice', max_length=20),
        ),
    ]
