# Generated by Django 2.0.2 on 2018-03-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='facility_ownership',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='facility_type',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='psk_region',
        ),
    ]
