# Generated by Django 2.0.2 on 2018-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_counties'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='constituency',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
