# Generated by Django 2.0.2 on 2018-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_auto_20180306_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='facility_ownership',
            field=models.CharField(default='', max_length=200),
        ),
    ]
