# Generated by Django 2.0.2 on 2018-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_auto_20180503_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
