# Generated by Django 2.0.2 on 2019-07-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_remove_facilities_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='countyy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilities.Counties'),
        ),
    ]
